---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5ffc7b8674b0b800152f8e83/webhook/forestry'
sections:
- type: document
  path: config.yaml
  label: Site Configuration
  templates:
  - config
- type: directory
  path: data/team
  label: Person
  create: all
  match: '**/*'
  new_doc_ext: yaml
  templates:
  - person
- type: directory
  path: data/categories
  label: Category
  create: all
  match: '**/*'
  new_doc_ext: yaml
  templates:
  - category
- type: directory
  path: content
  label: Pages
  create: all
  match: '**/*'
  new_doc_ext: md
  templates:
  - page
  - post
  - advanced
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.48'
